VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

# TODO: Remove this
VIAL_INSECURE = yes

NKRO_ENABLE = yes

# slimming down
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
# MUSIC_ENABLE = no

# BOOTLOADER = qmk-hid
# BOOTLOADER_SIZE = 512

MCU_LDSCRIPT = STM32F103x8_0x08006000_bootloader
DFU_ARGS = -d 1688:2220 -a 0 -s 0x08006000
DFU_SUFFIX_ARGS = -v 1688 -p 2220
BOOTLOADER_TYPE = stm32duino
OPT_DEFS += -DBOOTLOADER_STM32DUINO
